# Flyway in dev: run normal schema migrations + dev-only seed migrations
spring.flyway.locations=classpath:db/migration,classpath:db/migration-dev

# Invite sender for local/dev demo
app.invite.from-address=noreply.iksys@gmail.com

# Gmail SMTP for local/dev demo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.iksys@gmail.com
spring.mail.password=sxxiiqtdxgkulkqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
